import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/sidebar/app-sidebar";
import { TailwindIndicator } from "@/components/shared/tailwind-indicator";
import { auth } from "@/server/auth";
import { headers } from "next/headers";
import { Container } from "@/components/shared/container";
import { Toaster } from "@/components/ui/sooner";
import { QueryProvider } from "@/components/providers/query-client-provider";
import { Header } from "@/components/shared/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Toaster position="top-center" richColors />
            <SidebarProvider>
              <AppSidebar user={session?.user} />
              <SidebarInset className="w-full overflow-hidden bg-transparent">
                <div className="fixed top-0 z-[-2] h-full w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(60,60,120,0.5),rgba(0,0,0,0))]"></div>
                <Header user={session?.user} />
                <Container className="mx-auto mb-0 size-full px-4">
                  {children}
                </Container>
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
          <TailwindIndicator />
        </QueryProvider>
      </body>
    </html>
  );
}
